nginx:
   image: "nginx:latest"
   ports:
      - "80:80"
   volumes:
      - ./sites-available:/etc/nginx/sites-available
      - ./sites-available:/etc/nginx/sites-enabled
      - ./logs:/var/log/nginx
      - ./public_html:/usr/share/nginx/html
phpfpm:
   build: ./my_images/php7.4_fpm
   links:
      - "mariadb:database"
   ports:
      - "9000:9000"
   volumes:
       - ./public_html:/usr/share/nginx/html
mariadb:
   image: mariadb/server:latest
   container_name: database_container
   ports:
      - "3306:3306"
   volumes:
       - ./sql_dump:/sql_dump
   environment:
      MYSQL_ROOT_PASSWORD: leo0546
